#!/bin/bash

LANG=$1
if [ -z "$LANG" ]; then
    echo "Usage: $0 <lang>"
    exit 1
fi

NAME=$2
if [ -z "$NAME" ]; then
    NAME=$(basename $(pwd))
fi

LANGS="python py golang go rust rs empty"

if [[ ! $LANGS =~ (^|[[:space:]])$LANG($|[[:space:]]) ]]; then
    echo "Invalid language: $LANG"
    exit 1
fi

echo "Creating scaffold for $LANG"

YEAR=$(date +%Y)

# Write license
cat <<EOF > LICENSE
MIT License

Copyright (c) ${YEAR} vcokltfre

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
EOF

# Write README
cat <<EOF > README.md
# ${NAME}

...

## License

This project is licensed under the MIT license. See the [LICENSE](./LICENSE) file for more info.
EOF

# Initialise git
git init

function setup_python() {
    curl -o .gitignore https://raw.githubusercontent.com/github/gitignore/master/Python.gitignore
}

function setup_golang() {
    go mod init github.com/vcokltfre/${NAME}

    cat <<EOF > main.go
package main

func main() {}
EOF

    echo ".env" >> .gitignore
}

function setup_rust() {
    cargo init
    echo ".env" >> .gitignore
}

if [ "$LANG" = "python" ] || [ "$LANG" = "py" ]; then
    setup_python
elif [ "$LANG" = "golang" ] || [ "$LANG" = "go" ]; then
    setup_golang
elif [ "$LANG" = "rust" ] || [ "$LANG" = "rs" ]; then
    setup_rust
fi
